server:
  port: 8080

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/shop_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_51TzuNWJ0QDMNUIImZTHtWVJKkPJq7kj5KaPNFwc3u8WpxUMBB8mkUaxLsUyV70sBs1OuIqHFJh6OQ7X24tYW3HJF00zdKXQF1O}